### ISSUE TITLE
Implement Generic Command Modeling

### ISSUE THREAD

**Issue by thatmattlove** [thatmattlove/hyperglass#110]
See #95 

#### 2021 05 27 Edit

I'm modifying this issue to encompass a discussed and highly-requested ability to implement arbitrary commands that are in no way linked to address-family or VRFs, and only optionally use built-in validation.

**Comment by brevius** [comment]
+1 for that feature 👍 
Would it be possible to allow more commands definitions/customization - in addition to those 5 already implemented (bgp, ping traceroute)?
Something like raw output from defined query.

**Comment by checktheroads** [comment]
Hey @brevius - we were discussing this on Telegram the other day, and I agree that we need to genericize the commands so that we end up with built-in commands that are fully validated (and parsed for consumption in a table, where possible), with the ability to add arbitrary commands as well. I've been thinking about various ways to handle this and I think I have some good ideas. I have a lot going on at work in the next couple of weeks, but I'll try to get it done as quickly as possible.

**Comment by warriorsoul15** [comment]
These are cisco nxos commands but these are my top 3..

    bgp_summary: "show ip bgp summary"
    bgp_peer_received: "show bgp ipv4 unicast neighbor {target} received-routes"
    bgp_peer_advertised: "show bgp ipv4 unicast neighbor {target} advertised-routes"

**Comment by brevius** [comment]
Something usefull for JunOS:
bgp_peer_discarded: "show route receive-protocol bgp {target} table {vrf}.inet.0 hidden"

**Comment by streamthing** [comment]
What about this issue? Will it be done?

**Comment by thatmattlove** [comment]
@streamthing The vast majority of this _is_ done in the v2.0.0 branch. Unfortunately, I've had a number of personal and professional obstacles over the past several months that's prevented me from working on much of anything development-related, hyperglass included. I'm hoping to get back to it very soon, though.

The v2.0.0 branch should be usable-ish, you'd just have to _really_ study the codebase to get it working with custom generic commands, as one of the primary things left to do prior to release is write documentation.

**Comment by streamthing** [comment]
@thatmattlove No problem, I'll wait for v2.0.0.
Great work, it's works very well! <3
