### ISSUE TITLE
No outbound connections to router, or error log indicating failure

### ISSUE THREAD

**Issue by andrewcaustralia** [thatmattlove/hyperglass#163]
Any queries run against the LG time out with no error message shown, or connections made to the routers listed.
Error log doesn't show any relevant info (and in fact records no records at the time).

# Bug Description
Hyperglass installation, setup, and build-ui complete correctly - nginx is being used in front of the hyperglass service and website is reachable - but all commands issued timeout with a red error bar and no further information in the /tmp/hyperglass.log

Analysis of outbound traffic from the server indicate that at present the service never attempts to reach out to the routers (no packets are seen generated), but access via ssh on console has been confirmed to work normally.

# Steps to Reproduce

Head to the live lg: lg.gigafy.com.au - and attempt a ping/traceroute etc on any of the listed routers

## Local Configurations

Local configuration files (devices.yaml and hyperglass.yaml) have been attached with private information removed.

[devices.yaml.txt](https://github.com/thatmattlove/hyperglass/files/7064210/devices.yaml.txt)
[hyperglass.yaml.txt](https://github.com/thatmattlove/hyperglass/files/7064211/hyperglass.yaml.txt)

## Logs

Last events in /tmp/hyperglass.log are as follows:

```
[DEBUG] 20210825 10:10:33 | hyperglass.util.frontend:308 | build_frontend → node_modules is already initialized
[DEBUG] 20210825 10:10:34 | hyperglass.util.frontend:330 | build_frontend → Generated 21 favicons
[DEBUG] 20210825 10:10:34 | hyperglass.util.frontend:346 | build_frontend → Previous Build ID: beca46d9612bb29ae3446fba33a64404da64ac1dbef634dc1c90284fe402dce0
[DEBUG] 20210825 10:10:34 | hyperglass.util.frontend:351 | build_frontend → UI parameters unchanged since last build, skipping UI build...
[SUCCESS] 20210825 10:10:34 | hyperglass.main:138 | on_starting → Started hyperglass 1.0.4 on http://127.0.0.1:8001 with 1 workers
```

Console error seen in Chrome when request fails is as follows:

```
3index-e505c68071c2f6002cbe.js:1 Error
    at _app-b58f58e929193c09e5cc.js:1
    at l (main-efc23a685abfb580fb02.js:1)
    at Generator._invoke (main-efc23a685abfb580fb02.js:1)
    at Generator.throw (main-efc23a685abfb580fb02.js:1)
    at n (_app-b58f58e929193c09e5cc.js:1)
    at u (_app-b58f58e929193c09e5cc.js:1)
```

No error text is shown on the page itself.

# Possible Solution

Unsure of next steps - at present further logging might indicate where the issue lies but even with debug: true enabled in hyperglass.yaml I don't seem to be getting any further info.

# Environment

## Server

| Metric | Value |
| :----- | :---- |
| **hyperglass Version** | 1.0.4 |
| **hyperglass Path** | `None` |
| **Python Version** | `3.6.9` |
| **Node Version** | `14.17.5` |
| **Platform Info** | `Linux-4.15.0-33-generic-x86_64-with-Ubuntu-18.04-bionic` |
| **CPU Info** | Common KVM processor |
| **Logical Cores** | `2` |
| **Physical Cores** | `2` |
| **Processor Speed** | `2.095108GHz` |
| **Total Memory** | 4.14 GB |
| **Memory Utilization** | 10.7% |
| **Total Disk Space** | 19.99 GB |
| **Disk Utilization** | 22.3% |

## Client

- OS & Version: Windows 10
- Browser: Chrome 92.0.4515.131

**Comment by thatmattlove** [comment]
Have you tested this _not_ behind Cloudflare? It looks to me that the server is sending back a 502 (Bad Gateway) error:

<img width="830" alt="Screen Shot 2021-08-29 at 13 36 55" src="https://user-images.githubusercontent.com/42724207/131264648-763103c2-f16e-42a5-8bad-a3f695a06409.png">

In a typical environment where the user is hitting NGINX directly, we'd see an NGINX 502 error page, and it would usually indicate a problem with the NGINX config due to being unable to communicate with the backend hyperglass instance. However, with Cloudflare in the middle, I'm not exactly sure how that will be handled. Since the front end request is ultimately to `/api/query/`, which will also be handled by Cloudflare, I'm not sure if it's Cloudflare that's unable to communicate with NGINX, or NGINX that's unable to communicate with hyperglass.

If this still happens when not being Cloudflare, can you share your NGINX configuration as well?

**Comment by andrewcaustralia** [comment]
Looks like NGINX -> Hyperglass; I've disabled the cloudflare obfuscation for now and found there was a line in the NGINX config trying to use [::1]:8001 (which wasn't answering) rather than 127.0.0.1:8001

Was weird though as mentioned when running behind cloudflare the bad gateway error never showed.

All sorted! :-)
