### ISSUE TITLE
Enable password for Arista devices

### ISSUE THREAD

**Issue by mmarin11** [thatmattlove/hyperglass#183]
Hi Hyperglass community

I'm testing hyperglass with Arista devices and I'm getting the following error message

% Invalid input (privileged mode required)

It looks like I need to specify the enable password as the default user and password does not allow ping and show ip bgp commands. Is there a way to specify the enable password in the devices.yaml file?

Thank you

![image](https://user-images.githubusercontent.com/40378669/147868541-0a8e7c55-c0c9-425a-9878-5fbcdb86825d.png)

**Comment by ServerForge** [comment]
Little late here, ran into a similar issue. The problem you are having is because the ping/traceroute commands by default use the source address parameter which for some reason cannot be run unless you are in the privileged exec mode. You need to set the user your looking glass is using to automatically be in the privileged exec mode. Or change the commands to not use the source parameter and set the default interface for them in your arista config.
