### ISSUE TITLE
Node 14 is EOL since May 2023

### ISSUE THREAD

**Issue by mowoe** [thatmattlove/hyperglass#226]
As you can see from [this](https://github.com/nodesource/distributions#nodejs-release-calendar) graphic, Node 14 is EOL for several months now. 
And so is the script mentioned in the getting started guide used to install node.

(The same can be said for Python 3.6 btw)

This is really bad security practice and should be changed.

**Comment by thatmattlove** [comment]
I'm aware of this and am working on a new release as time permits. Please see the note on the readme:

> Unfortunately, I've been extremely busy in my work and personal life and haven't had a lot of time to dedicate to hyperglass recently. I'm hoping that will change soon, but in the meantime, hyperglass v1.0.0 might be unusable or unstable unless you're running Ubuntu 18.04, Python 3.6, and Node 14, which is probably a bad idea for security reasons. v2.0.0 is almost ready for release, but not quite yet.

**Comment by thatmattlove** [comment]
From the first part of the note:

> hyperglass is under active development via the [v2.0.0 branch](https://github.com/thatmattlove/hyperglass/tree/v2.0.0). No further changes will be made to the v1.0.0 branch.

At this time, I'm not willing to put any further development efforts into v1.0.0. You'd be surprised at what updating the Python or Node versions might break with the various dependencies of the project, and what upgrading those dependencies might break as well. v2.0.0 is _mostly_ usable. When I was working with a user to test it they ran into some runtime issues, but it's possible that was Linux-related and could be fixed now.

My current goal for the project is a ground-up rewrite in Go, borrowing a lot of the new configuration logic from v2. This will eliminate a lot of the past issues with the project since it'll be able to run as a single binary. I've already started on this, but as I mentioned, time is a factor out of my control at the moment.
